### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Wayder228** [Muqsit/MonsterSpawnerGenerator#2]
Please tell me, is it possible to make these dungeons spawn in the world world? or how does it work?

**Comment by TheLemzz** [comment]
Support. I would very much like to make a dungeon generator in the world "world" without additional world, because I use my generation of the world.

**Comment by Muqsit** [comment]
You may edit the PocketMine configuration to your liking:
```yaml
worlds:
  world:
    generator: normal_msp
```
